#!/usr/bin/env python3

import argparse
import cProfile
import concurrent.futures
import io
import itertools
import logging
import multiprocessing as mp
import os
import pstats
import shutil
import sys
import time
from typing import cast
import networkx as nx
import yaml
import traceback

from hakc.HAKCCompartmentalization import HAKCCompartmentalization
from hakc.HAKCDatabase import HAKCDatabase
from hakc.HAKCLogger import LoggingLevelEnum, parse_log_level, setup_logging, HAKCLogger
from hakc.HAKCObjects import HAKCSymbol, HAKCFunction, HAKCGlobalVariable, \
    HAKCCompartment, HAKCDivision, HAKCCompartmentalizationAdjustment

logging.setLoggerClass(HAKCLogger)

logger: HAKCLogger = cast(HAKCLogger, logging.getLogger('hakc-static-analysis'))

def batched(iterable, n):
    if n < 1:
        raise ValueError('n must be at least one')
    iterator = iter(iterable)
    while batch := tuple(itertools.islice(iterator, n)):
        yield batch


def parse_yaml(filename: str, debug = False):
    logger.add_file_handler(filename.replace(".dag.yml",".static-analysis.log"))
    # parse_yaml needed here instead of in compartmentalization for use in multithreading
    # HAKCCompartmentalization.add_yaml_constructors()
    # logger.error(f"parsing {filename}")
    HAKCCompartmentalization.add_yaml_constructors()
    with open(filename, 'rb') as f:
        try:
            compartmentalization = yaml.load(f, Loader=yaml.Loader)
            logger.debug(f"Loaded {compartmentalization} from {filename}")
            return compartmentalization
        except Exception as e:
            logger.fatal(f"Failed to load yaml with error: {str(e)} in {filename}")
            traceback.print_exc()



def compute_dag_edge_weight(**kwargs) -> int:
    edge_weight = 0

    if kwargs.get(HAKCFunction.relation_indirect_calls, False):
        edge_weight += 1

    if kwargs.get(HAKCFunction.relation_direct_calls, False):
        edge_weight += 1

    if kwargs.get(HAKCSymbol.relation_symbol, False):
        edge_weight += 1

    return edge_weight


def compute_dag_edges_for_symbol_with_conn(conn: HAKCDatabase, symbol_hash: int):
    results = list()
    tail_hash_types = conn.get_dag_computation_edges(symbol_hash)
    dag_info = dict()

    for dag_edge_type, tail_hashes in tail_hash_types.items():
        for tail_hash in tail_hashes:
            if tail_hash not in dag_info:
                dag_info[tail_hash] = dict()
            dag_info[tail_hash][dag_edge_type] = True
    for tail_hash, tail_info in dag_info.items():
        dag_weight = compute_dag_edge_weight(**tail_info)
        if dag_weight > 0:
            results.append((symbol_hash, tail_hash, dag_weight))

    return results


mp_conn: HAKCDatabase | None = None


def init_mp_database(db_dir: str):
    global mp_conn
    mp_conn = HAKCDatabase(db_dir, read_only=True)

def compute_dag_edges_for_symbol(symbol_hashes):
    global mp_conn
    conn = mp_conn
    results = list()
    for symbol_hash in symbol_hashes:
        try:
            for t in compute_dag_edges_for_symbol_with_conn(conn, symbol_hash):
                results.append(t)
        except Exception as e:
            raise RuntimeError(f'compute_dag_edges_for_symbol failed for {symbol_hash}: {str(e)}')

    return results

def create_compartmentalization_single_thread(files: set[str], conn: HAKCDatabase) -> HAKCCompartmentalization:
    compartmentalization = HAKCCompartmentalization()
    for filename in logger.progress_bar(iterable=sorted(files), desc='Parsing YAML'):
        subG = parse_yaml(filename, True)
        # logger.debug(f'Found {subG}')
        if subG:
            compartmentalization = nx.compose(compartmentalization, subG)
        else:
            logger.error(f"Loaded compartmentalization is None!")
    logger.info(f'Adding compartmentalization')
    compartmentalization.add_default_compartmentalization(conn)
    compartmentalization.persist_to_database(conn, create_schema=True)
    return compartmentalization

def create_dag_single_thread(files: set[str], conn: HAKCDatabase) -> HAKCCompartmentalization:

    compartmentalization = create_compartmentalization_single_thread(files, conn)

    dag_edges = dict()
    dag_edges_added = 0
    symbols = compartmentalization.get_symbols()
    for symbol in logger.progress_bar(iterable=symbols, desc='DAG Edge computation'):
        for (head_hash, tail_hash, dag_edge_weight) in compute_dag_edges_for_symbol_with_conn(conn, hash(symbol)):
            if head_hash not in dag_edges:
                dag_edges[head_hash] = dict()
            dag_edges[head_hash][tail_hash] = dag_edge_weight
            tail_symbol = compartmentalization.get_symbol_by_hash(tail_hash)
            compartmentalization.add_dag_edge(symbol, tail_symbol, dag_edge_weight=dag_edge_weight)
            dag_edges_added += 1
    logger.info(f'Adding {dag_edges_added} DAG edges to compartmentalization')
    conn.persist_dag_edges(dag_edges)
    logger.info(f'Adding compartmentalization')
    # compartmentalization.add_default_compartmentalization(conn)
    return compartmentalization


def adjust_compartmentalization(db_dir: str, adjustment: HAKCCompartmentalizationAdjustment):
    logger.info(f'Adjusting DAG')
    conn = HAKCDatabase(db_dir)

    symbols = conn.get_symbols()
    assert len(symbols) != 0, f"No symbols were returned from database!"
    compartmentalization = HAKCCompartmentalization()
    nec_division = None
    no_enforcement_compartment = None
    if adjustment.add_no_enforcement_compartment:
        nec_division = HAKCDivision(HAKCCompartmentalization.no_enforcement_division)
        no_enforcement_compartment = HAKCCompartment(HAKCCompartmentalization.no_enforcement_compartment_id)
        compartmentalization.add_division(nec_division, no_enforcement_compartment)

    for symbol in logger.progress_bar(iterable=symbols, desc='Adjusting Compartmentalization'):
        compartmentalization.add_symbol(symbol, already_persisted=True)
        adjustments = adjustment.get_adjusted_division_and_compartment(symbol.definition_location.defining_file if symbol.definition_location else None)
        adjusted_division = None
        adjusted_compartment = None
        if adjustments is None:
            if adjustment.add_no_enforcement_compartment:
                adjusted_division = nec_division
                adjusted_compartment = no_enforcement_compartment
            else:
                adjustments = conn.get_division_id_compartment_id_from_symbol(symbol)
                if adjustments is None:
                    logger.error(f'Could not find original division for {symbol}')
                    continue

        if adjustments is not None:
            adjusted_division, adjusted_compartment = adjustments

        if adjusted_division is not None:
            if adjusted_division != nec_division:
                logger.info(f'{symbol} is moving to {adjusted_division}')
            else:
                logger.debug(f'{symbol} is moving to {adjusted_division}')
            compartmentalization.set_symbol_division_by_object(symbol, adjusted_division, adjusted_compartment)
        else:
            logger.info(f'{symbol} is unchanged')

    logger.info(f'Removing existing compartments')
    conn.delete_all_compartments()
    compartmentalization.persist_to_database(conn)
    logger.info(f'Done adjusting compartmentalization')
    logger.info(f'Compartmentalization now has {len(conn.get_all_divisions())} divisions across {len(conn.get_all_compartments())} compartments')
    conn.close()


def node_with_max_edges(graph):
    """
    Finds the node with the most edges in a NetworkX graph.

    Args:
      graph: A NetworkX graph object.

    Returns:
      The node with the maximum degree, or None if the graph is empty.
    """
    if not graph.nodes:
        return None
    return max(graph.degree, key=lambda item: item[1])[0]

def create_compartmentalization_multithread(files: set[str], core_count: int, conn: HAKCDatabase) -> HAKCCompartmentalization:
    import traceback

    logger.info(f'Starting multiprocess HAKCCompartmentalization creation using {core_count} cores')

    with concurrent.futures.ProcessPoolExecutor(max_workers=core_count) as executor:
        futures_to_files = {}
        for file in logger.progress_bar(iterable=sorted(files), desc="YAML parsing scheduling"):
            futures_to_files[executor.submit(parse_yaml, file)] = file
        compartmentalization = HAKCCompartmentalization()
        compartmentalization.create_schema(conn)
        with logger.progress_bar(total=len(files), desc='YAML parsing results') as pbar:
            for future in list(concurrent.futures.as_completed(futures_to_files)):
                pbar.update(1)
                file = futures_to_files[future]
                try:
                    subG = future.result()
                    # Note: nx.union requires graphs be disjoint, so use nx.compose instead
                    if subG:
                        compartmentalization = nx.compose(compartmentalization, subG)
                    else:
                        logger.error(f"Loaded compartmentalization is None!")

                except Exception as e:
                    traceback.print_exc()
                    logger.error(f'Error parsing {file}: {str(e)} with {subG}')

    logger.info(f'Adding compartmentalization')
    compartmentalization.add_default_compartmentalization(conn)
    compartmentalization.persist_to_database(conn)
    # logger.info(f'Total symbols {len(conn.get_symbols())}')
    return compartmentalization


def create_dag_multithread(files: set[str], core_count: int, conn: HAKCDatabase) -> HAKCCompartmentalization:

    logger.info(f'Starting multiprocess DAG creation using {core_count} cores')

    compartmentalization = create_compartmentalization_multithread(files, core_count, conn)

    conn.close()
    with concurrent.futures.ProcessPoolExecutor(max_workers=core_count, initializer=init_mp_database,
                                                initargs=(conn.db_dir,)) as executor:
        dag_edges_added = 0
        symbol_hashes = compartmentalization.get_symbol_hashes()
        batch_size = 100
        futures = list()
        with logger.progress_bar(total=int(len(symbol_hashes) / batch_size) + 1,
                                 desc='DAG Edge computation scheduling') as pbar:
            try:
                for symbol_hash_batch in batched(symbol_hashes.keys(), batch_size):
                    future = executor.submit(compute_dag_edges_for_symbol, symbol_hash_batch)
                    futures.append(future)
                    pbar.update(1)
            except Exception as e:
                logger.error(f'Error submitting tasks: {str(e)}')
                executor.shutdown(wait=False, cancel_futures=True)
                raise e

        with logger.progress_bar(total=len(futures), desc='DAG Edge addition') as pbar:
            try:
                dag_edges = dict()
                for future in concurrent.futures.as_completed(futures):
                    pbar.update(1)
                    try:
                        edge_weights = future.result()
                        for (head_hash, tail_hash, dag_edge_weight) in edge_weights:
                            if head_hash not in dag_edges:
                                dag_edges[head_hash] = dict()
                            head_symbol = symbol_hashes[head_hash]
                            tail_symbol = symbol_hashes[tail_hash]
                            compartmentalization.add_dag_edge(head_symbol, tail_symbol, dag_edge_weight=dag_edge_weight)
                            dag_edges[head_hash][tail_hash] = dag_edge_weight
                            dag_edges_added += 1
                    except Exception as e:
                        logger.error(f'Error computing DAG edge: {str(e)}')
            except KeyboardInterrupt as ki:
                logger.info(f'Stopping edge computation')
                executor.shutdown(wait=False, cancel_futures=True)
                raise ki

    logger.info(f'Adding {dag_edges_added} DAG edges to compartmentalization')
    conn.open(max_num_threads=core_count)
    conn.persist_dag_edges(dag_edges)
    if conn:
        conn.close()
    return compartmentalization


def create_new_dag(analysis_root: str, core_count: int, db_dir: str,
                   delete_existing_db: bool) -> HAKCCompartmentalization:
    logger.info(f'Finding DAG files starting from {os.path.abspath(analysis_root)}')
    single_thread = core_count == 1
    filenames = set()
    for root, subdirs, files in os.walk(analysis_root):
        for f in files:
            filename = os.path.join(root, f)
            if not filename.endswith(".dag.yml"):
                continue
            filenames.add(str(filename))

    if len(filenames) == 0:
        raise RuntimeError(f"Unable to find any .dag.yml files under root: {os.path.abspath(analysis_root)}")
    if delete_existing_db:
        if os.path.exists(db_dir) and os.path.isdir(db_dir):
            logger.info(f'Removing existing database at {db_dir}')
            shutil.rmtree(db_dir)

    conn = HAKCDatabase(db_dir, max_num_threads=core_count)
    logger.info(f'Starting DAG construction from {len(filenames)} files')
    start = time.time()
    if single_thread:
        compartmentalization = create_dag_single_thread(filenames, conn)
    else:
        core_count = min(max(1, core_count), 100)
        compartmentalization = create_dag_multithread(filenames, core_count, conn)

    end = time.time()
    logger.info(f'Finished creating DAG.')
    logger.info(f'    Total Time: {end - start} seconds')
    logger.info(f'    Type Count: {len(compartmentalization.get_types())}')
    logger.info(f'  Global Count: {len(compartmentalization.get_global_variables())}')
    logger.info(f'Function Count: {len(compartmentalization.get_functions())}')
    return compartmentalization


def print_edge_data(G):
    for edge in G.edges:
        print(f"Edge: {edge} -> {G.get_edge_data(edge[0], edge[1])}")


def output_profile_stats(profile):
    s = io.StringIO()
    ps = pstats.Stats(profile, stream=s).sort_stats('tottime')
    ps.print_stats()
    logger.info(s.getvalue())


def main():
    parser = argparse.ArgumentParser(description='Kernel Data Access Analysis')
    parser.add_argument('--dag-files-root', help='Root of DAG Yaml files', dest='dag_files_root')
    parser.add_argument('--log-level', required=False, dest='log_level', default=LoggingLevelEnum.INFO,
                        help=f'Log level to display, can be lower case {[level.name for level in LoggingLevelEnum]}',
                        type=parse_log_level)
    parser.add_argument('-l', '--log', default=None, dest='log_path')
    parser.add_argument('--log-mode', default='w', dest='log_mode')
    parser.add_argument('--create-dag', dest='create_dag', action='store_true', help='Create new DAG')
    parser.add_argument("--adjust", help='Adjust compartmentalization', action='store_true')
    parser.add_argument('--adjust-path', dest='adjust_path', help='Path to adjustment YAML')
    parser.add_argument('--profile', dest='profile', action='store_true')
    parser.add_argument('--core-count', help='Max cores to use for analysis', dest='core_count',
                        default=mp.cpu_count() - 1, type=int)
    parser.add_argument('--db-dir', help='Directory to use for the kuzu database', dest='db_dir',
                        default=None)
    parser.add_argument('--delete-existing-db', help='Deletes existing database when creating a new compartmentalization', dest='delete_db', action='store_true')
    parser.add_argument('--dump-dag', dest='dump_dag', help='dump DAG to yaml')
    parser.add_argument('--load-dag', dest='load_dag', help='load DAG from yaml')

    args = parser.parse_args()

    root_logger: HAKCLogger = cast(HAKCLogger, logging.getLogger()) # cast suppresses type hint warning
    setup_logging(root_logger, log_level=args.log_level, log_file=args.log_path, log_mode=args.log_mode)
    profile = None

    if args.db_dir is None or len(args.db_dir) == 0:
        raise RuntimeError(f'Must specify a database directory')

    logger.info(f'Using database at {args.db_dir}')
    compartmentalization = None

    if args.profile:
        profile = cProfile.Profile()

    HAKCCompartmentalization.add_yaml_constructors()
    if args.create_dag:
        if profile:
            profile.enable()
        compartmentalization = create_new_dag(args.dag_files_root, args.core_count, args.db_dir, args.delete_db)
        if profile:
            profile.disable()
            output_profile_stats(profile)

    if args.adjust:
        logger.info(f'Adjusting compartmentalization based on {args.adjust_path}')
        with open(args.adjust_path, 'r') as f:
            adjustments = yaml.load(f, Loader=yaml.Loader)
        adjust_compartmentalization(args.db_dir, adjustments)
        logger.info("Done")

    if args.dump_dag:
        compartmentalization.save_as_yaml(args.dump_dag)

if __name__ == "__main__":
    main()
    sys.exit(0)
