#!/usr/bin/env python3
import argparse
import logging
import multiprocessing as mp
import signal
from typing import cast

import yaml

from hakc.HAKCAnalysisServer import HAKCAnalysisServer, global_queue, SaveDAGEvent
from hakc.HAKCCompartmentalization import HAKCCompartmentalization
from hakc.HAKCLogger import LoggingLevelEnum, parse_log_level, setup_logging, HAKCLogger
from hakc.HAKCServerConfig import HAKCServerConfig, TimeoutException

logging.setLoggerClass(HAKCLogger)

logger = logging.getLogger('hakc-analysis-server-process')

def timeout_handler(signum, frame):
    raise TimeoutException

def merger_thread(dag_path: str):
    # using global variables global_queue, SaveDAGEvent
    logger.info(f"Spinning up HAKCCompartmentalization thread!")
    global_compartmentalization = HAKCCompartmentalization()

    while True:
        if global_queue.empty():
            if SaveDAGEvent.is_set():
                # queue must be empty before thread can exit
                logger.info(f"Got SaveDAGEvent signal")
                logger.info(f"Saving DAG {global_compartmentalization}")
                global_compartmentalization.save_as_yaml(dag_path)
                logger.info(f"Saved DAG to {dag_path}")
                SaveDAGEvent.clear()
                return
            continue
        subG = global_queue.get()
        if subG:
            global_compartmentalization.update(edges=subG.edges(data=True, keys=True),
                                               nodes=subG.nodes(data=True))
            logger.info(f"""\tMerged {global_compartmentalization} with
                                    {len(global_compartmentalization.get_types())}\tTypes
                                    {len(global_compartmentalization.get_scopes())}\tScopes
                                    {len(global_compartmentalization.get_global_variables())}\tGlobal Variables
                                    {len(global_compartmentalization.get_functions())}\tFunctions""")

# noinspection PyTypeChecker
def main():
    parser = argparse.ArgumentParser(description='HAKC Analysis Server Process')
    parser.add_argument('--config', help='Path to config file', required=True)
    parser.add_argument('--log-level', required=False, dest='log_level', default=LoggingLevelEnum.INFO,
                        help=f'Log level to display, can be lower case {[level.name for level in LoggingLevelEnum]}',
                        type=parse_log_level)
    parser.add_argument('-l', '--log', default=None, dest='log_path')
    parser.add_argument('--log-mode', default='w', dest='log_mode')
    parser.add_argument('--no-timeout', required=False, dest='no_timeout', action='store_true',
                        help='Ignore timeout in config file')

    args = parser.parse_args()
    setup_logging(logger, log_file=args.log_path, log_level=args.log_level, log_mode=args.log_mode)
    with open(args.config, 'r') as f:
        parsed_config = yaml.safe_load(f)
        config = HAKCServerConfig(**parsed_config)
        if args.no_timeout:
            config.server_timeout = -1

    # setting up root logger, which all other loggers should inherit its properties (unless we overwrite them later)
    # need to set up server logger here, or else all the initialization stuff will happen without debugging
    # loggers that are used in the data_source files need to be initialized BEFORE the init_data_source function is called
    root_logger = logging.getLogger()
    setup_logging(root_logger, log_level=args.log_level, log_file=args.log_path if args.log_path else '', log_mode=args.log_mode)
    AnalysisServerMainLogger: HAKCLogger = cast(HAKCLogger, logging.getLogger('hakc-analysis-server-main'))
    if config.log_path:
        AnalysisServerMainLogger.add_file_handler(config.log_path)
    proc = mp.Process(target=merger_thread, args=(config.dag_path,))
    proc.start()
    with HAKCAnalysisServer(config, AnalysisServerMainLogger) as server:
        try:
            if config.server_timeout > 0:
                signal.signal(signal.SIGALRM, timeout_handler)
                signal.alarm(config.server_timeout)
            server.serve_forever()
        except KeyboardInterrupt:
            AnalysisServerMainLogger.info('Analysis Server received User KeyboardInterrupt Exception')
        except TimeoutException:
            AnalysisServerMainLogger.info(f'Analysis Server received Timeout Exception')
        except Exception as e:
            AnalysisServerMainLogger.error(f'Analysis Server received generic Exception: {e}')
        finally:
            server.server_close()
    # logger.info(f"Setting SaveDAGEvent signal")
    SaveDAGEvent.set()
    # logger.error(f"Joining merger proc")
    global_queue.close()
    # logger.error(f"closed queue")
    # global_queue.join_thread()
    # logger.error(f"joined queue")
    proc.join()

if __name__ == "__main__":
    main()
