#!/usr/bin/env python3
import argparse
import logging
import unittest
from typing import cast

import hakc.tests.HAKCSpatialTests as HAKCSpatialTests
from hakc.HAKCLogger import LoggingLevelEnum, parse_log_level, setup_logging, HAKCLogger

logging.setLoggerClass(HAKCLogger)

logger = cast(HAKCLogger, logging.getLogger('hakc.test-process'))

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='HAKC Analysis Server Process')
    parser.add_argument('--log-mode', default='w', dest='log_mode')
    parser.add_argument('--log-level', required=False, dest='log_level',
                        help=f'Log level to display, can be lower case {[level.name for level in LoggingLevelEnum]}',
                        type=parse_log_level, default=LoggingLevelEnum.INFO)
    args = parser.parse_args()

    root_logger = logging.getLogger()
    setup_logging(root_logger, log_level=args.log_level, log_mode=args.log_mode)
    # setting compartmentalization log level to disable the progress bars
    compartmentalization_logger: HAKCLogger = cast(HAKCLogger, logging.getLogger('hakc.test.compartmentalization'))
    setup_logging(compartmentalization_logger, log_level=args.log_level, log_mode=args.log_mode)

    loader = unittest.TestLoader()
    suite_a = loader.loadTestsFromTestCase(HAKCSpatialTests.HAKCDatabaseTests)

    runner = unittest.TextTestRunner(verbosity=0)
    runner.run(suite_a)
