#!/usr/bin/env python3
import argparse
import logging
import signal
from typing import Optional, cast

import yaml

from hakc.HAKCLogger import LoggingLevelEnum, parse_log_level, setup_logging, HAKCLogger
from hakc.HAKCAnalysisServer import HAKCAnalysisServer
from hakc.HAKCServerConfig import HAKCServerConfig, TimeoutException
logging.setLoggerClass(HAKCLogger)

logger = logging.getLogger('hakc-analysis-server-process')

def timeout_handler(signum, frame):
    raise TimeoutException


# noinspection PyTypeChecker
def main():
    parser = argparse.ArgumentParser(description='HAKC Analysis Server Process')
    parser.add_argument('--config', help='Path to config file', required=True)
    parser.add_argument('--log-level', required=False, dest='log_level', default=LoggingLevelEnum.INFO,
                        help=f'Log level to display, can be lower case {[level.name for level in LoggingLevelEnum]}',
                        type=parse_log_level)
    parser.add_argument('-l', '--log', default=None, dest='log_path')
    parser.add_argument('--log-mode', default='w', dest='log_mode')
    parser.add_argument('--no-timeout', required=False, dest='no_timeout', action='store_true',
                        help='Ignore timeout in config file')

    args = parser.parse_args()
    setup_logging(logger, log_file=args.log_path, log_level=args.log_level, log_mode=args.log_mode)
    with open(args.config, 'r') as f:
        parsed_config = yaml.safe_load(f)
        config = HAKCServerConfig(**parsed_config)
        if args.no_timeout:
            config.server_timeout = -1

    # setting up root logger, which all other loggers should inherit its properties (unless we overwrite them later)
    # need to set up server logger here, or else all the initialization stuff will happen without debugging
    # loggers that are used in the data_source files need to be initialized BEFORE the init_data_source function is called
    root_logger = logging.getLogger()
    setup_logging(root_logger, log_level=args.log_level, log_file=args.log_path if args.log_path else '', log_mode=args.log_mode)
    AnalysisServerMainLogger: HAKCLogger = cast(HAKCLogger, logging.getLogger('hakc-analysis-server-main'))
    if config.log_path:
        AnalysisServerMainLogger.add_file_handler(config.log_path)
    with HAKCAnalysisServer(config, AnalysisServerMainLogger) as server:
        try:
            if config.server_timeout > 0:
                signal.signal(signal.SIGALRM, timeout_handler)
                signal.alarm(config.server_timeout)
            server.serve_forever()
        except KeyboardInterrupt:
            AnalysisServerMainLogger.info('Analysis Server received User KeyboardInterrupt Exception')
        except TimeoutException:
            AnalysisServerMainLogger.info(f'Analysis Server received Timeout Exception')
        except Exception as e:
            AnalysisServerMainLogger.error(f'Analysis Server received generic Exception: {e}')
        finally:
            server.server_close()


if __name__ == "__main__":
    main()
