#!/usr/bin/env python3

import argparse
import cProfile
import logging
import multiprocessing as mp
import sys
from typing import cast

from hakc.HAKCCompartmentalization import HAKCCompartmentalization
from hakc.HAKCDatabase import HAKCDatabase
from hakc.HAKCLogger import LoggingLevelEnum, parse_log_level, setup_logging, HAKCLogger
from hakc.HAKCStaticAnalysis import output_profile_stats

logging.setLoggerClass(HAKCLogger)

logger: HAKCLogger = cast(HAKCLogger, logging.getLogger('hakc-static-analysis-process'))

def main():
    parser = argparse.ArgumentParser(description='Kernel Data Access Analysis')
    # parser.add_argument('--dag-files-root', help='Root of DAG Yaml files', dest='dag_files_root')
    parser.add_argument('--dag-path', help='Path of DAG file', dest='dag_path')
    parser.add_argument('--log-level', required=False, dest='log_level', default=LoggingLevelEnum.INFO,
                        help=f'Log level to display, can be lower case {[level.name for level in LoggingLevelEnum]}',
                        type=parse_log_level)
    parser.add_argument('-l', '--log', default=None, dest='log_path')
    parser.add_argument('--log-mode', default='w', dest='log_mode')
    parser.add_argument('--create-dag', dest='create_dag', action='store_true', help='Create new DAG')
    parser.add_argument("--adjust", help='Adjust compartmentalization', action='store_true')
    parser.add_argument('--adjust-path', dest='adjust_path', help='Path to adjustment YAML')
    parser.add_argument('--profile', dest='profile', action='store_true')
    parser.add_argument('--core-count', help='Max cores to use for analysis', dest='core_count',
                        default=mp.cpu_count() - 1, type=int)
    parser.add_argument('--db-dir', help='Directory to use for the kuzu database', dest='db_dir', default=None)
    parser.add_argument('--delete-existing-db', help='Deletes existing database when creating a new compartmentalization', dest='delete_db', action='store_true')
    parser.add_argument('--dump-dag', dest='dump_dag', help='dump DAG to yaml')
    parser.add_argument('--load-dag', dest='load_dag', help='load DAG from yaml')

    args = parser.parse_args()

    root_logger: HAKCLogger = cast(HAKCLogger, logging.getLogger()) # cast suppresses type hint warning
    setup_logging(root_logger, log_level=args.log_level, log_file=args.log_path, log_mode=args.log_mode)

    if args.db_dir is None or len(args.db_dir) == 0:
        raise RuntimeError(f'Must specify a database directory')

    logger.info(f'Using database at {args.db_dir}')
    HAKCCompartmentalization.add_yaml_constructors()

    profile = None
    compartmentalization = None

    if args.profile:
        profile = cProfile.Profile()
        profile.enable()

    if args.delete_db:
        HAKCCompartmentalization.delete_db(args.db_dir)

    if args.create_dag:
        compartmentalization = HAKCCompartmentalization.parse_yaml(args.dag_path)
        logger.info(f"\tLoaded {compartmentalization}")
        compartmentalization.create_new_db(args.db_dir)
        compartmentalization.add_default_compartmentalization(args.db_dir)
        compartmentalization.create_dag(args.core_count, args.db_dir)

    if args.adjust:
        compartmentalization.adjust_compartmentalization(args.adjust_path, args.db_dir)

    if args.dump_dag:
        compartmentalization.save_as_yaml(args.dump_dag)

    if args.profile:
        profile.disable()
        output_profile_stats(profile)

if __name__ == "__main__":
    main()
    sys.exit(0)
